name: jsonIntegrationTest
apis:
  - name: readEtcdSelfJson
    file: $$MY_TEMP_FOLDER\etcdSelf.json
    remove_keys:
      - leaderInfo
  - name: readEtcdSelfLeaderInfo
    file: $$MY_TEMP_FOLDER\etcdSelf.json
    start_key:
      - leaderInfo
    rename_keys:
      startTime: timestamp
