integrations:
  - name: nri-flex
    # embedded Flex configuration.
    # config:
    #   - name: example
    #     apis:
    #      - name: status 
    #        commands:
    #          - run: echo "hello:world"
    #            split_by: ":"

    # external configuration file (single file support only)
    # config_template_path: /etc/newrelic-infra/integrations.d/flex.yml

    env:
      # multiple external file configuration support
      CONFIG_DIR: /etc/newrelic-infra/integrations.d/flexConfigs
      # GIT_REPO: https://github.com/userName/repoName
      # GIT_USER: userName
      # GIT_TOKEN: abcd
      # EVENT_LIMIT: 500 ## default 500
      # INSIGHTS_API_KEY: abc
      # INISGHTS_URL: https://insights...
      # INSIGHTS_OUTPUT: false ## output the payload to stdout (default false)
    # labels:
      # owner: cloud